USE EXERCICIO_1_3;

INSERT INTO RACA(NOME)
VALUES 
('GIOVANNI'),
('LICAS'),
('YESI'),
('FIORINO');

INSERT INTO TYPEPET(NOME)
VALUES 
('DRAGAO'),
('VOADOR'),
('DARK'),
('NORMAL');

INSERT INTO DONOS(NOME)
VALUES 
('TOMAS'),
('YUTI'),
('GOES'),
('LUIS');

INSERT INTO VETERINARIO(IDCLINICA,NOME)
VALUES 
(1,'EHGRG'),
(1,'GEEG'),
(2,'GEGEG'),
(3,'ERG');

INSERT INTO CLINICA(IDENDERECO,NOME)
VALUES
('1','CANECOS'),
('1','WELCOME TO THE PET HELL'),
('2','HEALPET'),
('3','NORMAL');

INSERT INTO ENDERECO(LOGRADOURO,NUMERO,BAIRRO,CIDADE,ESTADO,COMPLEMENTO)
VALUES
('RUA DOUGLAS','34','ROCINHA','SA','SP','-'),
('RUA TRES MARIAS','23','ROCINHA','SA','SP','FUNDO'),
('RUA IGNIS DOMUS NECRONINE','789','ALFAVILLE','EL DORADO GRANDE ROCHA','MANAUS','TURQUESA')

INSERT INTO PETS(IDVETERINARIO,IDDONO,IDRACA,IDTYPEPET,NOME)
VALUES ('1','2','1','3','TUTU'),
('3','2','2','3','YOP'),
('2','1','1','2','HUGO'),
('2','1','1','1','KYLE');

INSERT INTO ATENDIMENTO(IDPET,IDVETERINARIO,NºPROTOCOLO)
VALUES (1,1,'Nº14534562849209473'),
(2,3,'Nº14534251049209473'),
(3,1,'Nº184925654652778223')

SELECT * FROM RACA
SELECT * FROM TYPEPET
SELECT * FROM DONOS
SELECT * FROM VETERINARIO
SELECT * FROM CLINICA
SELECT * FROM ENDERECO
SELECT * FROM PETS
SELECT * FROM ATENDIMENTO