CREATE DATABASE EXERCICIO_1_3;
GO
USE EXERCICIO_1_3;
GO
CREATE TABLE RACA
(
	IDRACA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50)
)
GO
CREATE TABLE TYPEPET
(
	IDTYPEPET INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50)
)
GO
CREATE TABLE DONOS
(
	IDDONO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50)
)
GO
CREATE TABLE VETERINARIO
(
	IDVETERINARIO INT PRIMARY KEY IDENTITY,
	IDCLINICA INT FOREIGN KEY REFERENCES CLINICA(IDCLINICA),
	NOME VARCHAR(50)
)
GO
CREATE TABLE CLINICA
(
	IDCLINICA INT PRIMARY KEY IDENTITY,
	IDENDERECO INT FOREIGN KEY REFERENCES ENDERECO(IDENDERECO),
	NOME VARCHAR(100)
)
GO
CREATE TABLE ENDERECO
(
	IDENDERECO INT PRIMARY KEY IDENTITY,
	LOGRADOURO VARCHAR(50),
	NUMERO VARCHAR(100),
	BAIRRO VARCHAR(100),
	CIDADE VARCHAR(100),
	ESTADO VARCHAR(100),
	COMPLEMENTO VARCHAR(100),
)
GO
CREATE TABLE PETS
(
	IDPET INT PRIMARY KEY IDENTITY,
	IDVETERINARIO INT FOREIGN KEY REFERENCES VETERINARIO(IDVETERINARIO),
	IDDONO INT FOREIGN KEY REFERENCES DONOS(IDDONO),
	IDTYPEPET INT FOREIGN KEY REFERENCES TYPEPET(IDTYPEPET),
	IDRACA INT FOREIGN KEY REFERENCES RACA(IDRACA),
	NOME VARCHAR(100)
)
GO
CREATE TABLE ATENDIMENTO
(
	IDATENDIMENTO INT PRIMARY KEY IDENTITY,
	IDPET INT FOREIGN KEY REFERENCES PETS(IDPET),
	IDVETERINARIO INT FOREIGN KEY REFERENCES VETERINARIO(IDVETERINARIO)
)
GO
ALTER TABLE PETS
ADD NOME VARCHAR(100)
GO

ALTER TABLE ATENDIMENTO
ADD NºPROTOCOLO VARCHAR(100)
GO

--SELECT
--FROM 
--WHERE