CREATE DATABASE PCLINICS_M;
GO

USE PCLINICS_M;
GO

CREATE TABLE CLINICA
(
    IDCLINICA		INT PRIMARY KEY IDENTITY (1,1)
    ,RAZAOSOCIAL    VARCHAR(200) NOT NULL UNIQUE
	,CNPJ		    CHAR(14) NOT NULL UNIQUE
	,ENDERECO	    VARCHAR(200) NOT NULL UNIQUE
);
GO

CREATE TABLE TIPOSPET
(
    IDTIPOPET	INT PRIMARY KEY IDENTITY
    ,DESCRICAO	VARCHAR(200) UNIQUE
);
GO

CREATE TABLE RACA
(
    IDRACA		INT PRIMARY KEY IDENTITY
    ,DESCRICAO	VARCHAR(200) UNIQUE NOT NULL
    ,IDTIPOPET  INT FOREIGN KEY REFERENCES TIPOSPET (IDTIPOPET)
);
GO

CREATE TABLE DONO
(
	IDDONO		INT PRIMARY KEY IDENTITY
	,NOME		VARCHAR(200) NOT NULL
);
GO

CREATE TABLE PET
(
    IDPET				INT PRIMARY KEY IDENTITY
    ,NOME				VARCHAR(200)
    ,DATANASCIMENTO		DATE
	,IDRACA				INT FOREIGN KEY REFERENCES RACA (IDRACA)
	,IDDONO				INT FOREIGN KEY REFERENCES DONO (IDDONO)
);
GO

CREATE TABLE VETERINARIO
(
    IDVETERINARIO   INT PRIMARY KEY IDENTITY
    ,NOME			VARCHAR(200)
	,CRMV			CHAR(6) UNIQUE
	,IDCLINICA		INT FOREIGN KEY REFERENCES CLINICA (IDCLINICA)
);
GO

CREATE TABLE ATENDIMENTO
(
    IDATENDIMENTO		INT PRIMARY KEY IDENTITY
    ,DESCRICAO			VARCHAR(200)
	,DATAATENDIMENTO	DATETIME NOT NULL
	,IDVETERINARIO		INT FOREIGN KEY REFERENCES VETERINARIO (IDVETERINARIO)
	,IDPET				INT FOREIGN KEY REFERENCES PET (IDPET)
);
GO