USE PCLINICS_M;
GO

SELECT * FROM CLINICA;
GO

SELECT * FROM TIPOSPET;
GO

SELECT * FROM RACA;
GO

SELECT * FROM DONO;
GO

SELECT * FROM VETERINARIO;
GO

SELECT * FROM PET;
GO

SELECT * FROM ATENDIMENTO;
GO

-- LISTAR TODOS OS VETERINÁRIOS (NOME E CRMV) DE UMA CLÍNICA (RAZÃO SOCIAL)
SELECT NOME, CRMV, RAZAOSOCIAL FROM VETERINARIO
INNER JOIN CLINICA
ON CLINICA.IDCLINICA = VETERINARIO.IDCLINICA
WHERE CLINICA.IDCLINICA = 1;

-- LISTAR TODAS AS RAÇAS QUE COMEÇAM COM A LETRA S
SELECT * FROM RACA
WHERE DESCRICAO LIKE 'S%';

-- LISTAR TODOS OS TIPOS DE PET QUE TERMINAM COM A LETRA O
SELECT * FROM TIPOSPET
WHERE DESCRICAO LIKE '%O';

-- LISTAR TODOS OS PETS MOSTRANDO OS NOMES DOS SEUS DONOS
-- ALIAS (APELIDO) AS
SELECT IDPET, PET.NOME PET, DATANASCIMENTO AS 'DATA NASCIMENTO', DONO.NOME AS DONO FROM PET
INNER JOIN DONO
ON PET.IDDONO = DONO.IDDONO;

-- LISTAR TODOS OS ATENDIMENTOS MOSTRANDO O NOME DO VETERINÁRIO QUE ATENDEU, 
-- O NOME, A RAÇA E O TIPO DO PET QUE FOI ATENDIDO,
-- O NOME DO DONO DO PET E O NOME DA CLÍNICA ONDE O PET FOI ATENDIDO
SELECT IDATENDIMENTO, V.NOME [VETERINÁRIO], P.NOME PET,
R.DESCRICAO [RAÇA], TP.DESCRICAO [ESPÉCIE], D.NOME DONO, RAZAOSOCIAL [RAZÃO SOCIAL]
FROM ATENDIMENTO AS A
LEFT JOIN VETERINARIO V
ON A.IDVETERINARIO = V.IDVETERINARIO
INNER JOIN PET P
ON A.IDPET = P.IDPET
INNER JOIN RACA R
ON P.IDRACA = R.IDRACA
INNER JOIN TIPOSPET TP
ON TP.IDTIPOPET = R.IDTIPOPET
INNER JOIN DONO D
ON P.IDDONO = D.IDDONO
INNER JOIN CLINICA C
ON C.IDCLINICA = V.IDCLINICA;