CREATE DATABASE inlock_games_bdFirst_manha

USE	inlock_games_bdFirst_manha
--
CREATE TABLE Estudio
(
	IdEstudio UNIQUEIDENTIFIER PRIMARY KEY ,
	Nome VARCHAR(100) NOT NULL
)
--
CREATE TABLE Jogo
(
	IdJogo UNIQUEIDENTIFIER PRIMARY KEY,
	IdEstudio UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Estudio(IdEstudio),
	Nome VARCHAR(100) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	DataLancamento DATE NOT NULL,
	Valor SMALLMONEY NOT NULL
)
--
CREATE TABLE TipoUsuario
(
	IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	Titulo VARCHAR(100)
)
--
CREATE TABLE Usuario 
(
	IdUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
	Email VARCHAR(100) NOT NULL,
	Senha VARCHAR(100) NOT NULL
)

INSERT INTO Estudio
VALUES (NEWID(),'SENAI'),(NEWID(),'SESI'),(NEWID(),'SEBRAE')

SELECT * FROM Estudio

INSERT INTO Jogo
VALUES (NEWID(),'F94DA7A9-2ED8-44B4-A5AC-72161211F87B','PING PONG','JOGO LEGAL','2023-01-01',500),
	   (NEWID(),'626C9F30-178C-4D5E-8158-BA7047DFA4D6','JUCAMON','SNORLAX','2023-03-23',2.99)

SELECT * FROM Jogo

INSERT INTO TipoUsuario
VALUES (NEWID(),'adm'),(NEWID(),'comum')

SELECT * FROM TipoUsuario

INSERT INTO Usuario
VALUES (NEWID(),'46C66CB6-BDB3-4E76-AB9A-9DC5DB140EE7','adm@kry.com','adm123'),
	   (NEWID(),'2EFAB602-A295-4C69-961E-AC6E9AA26697','comum@kry.com','comum123')


