CREATE DATABASE EXERCICIO_1_2;

USE EXERCICIO_1_2;
GO

CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100)
)

CREATE TABLE CLIENTE
(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100),
	CPF VARCHAR(11)
)

CREATE TABLE VEICULO
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdCliente INT FOREIGN KEY REFERENCES CLIENTE(IdCliente),
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa),
	Nome VARCHAR(100)
)
ALTER TABLE CLIENTE

ADD CPF VARCHAR(11) NOT NULL