--CRIA O BANCO DE DADOS
CREATE DATABASE TESTE;

GO

--USA O BANCO DE DADOS
USE TESTE;
GO
--CRIA UMA TABELA
CREATE TABLE Funcionarios
(
	IdFuncionario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100)
)
GO

CREATE TABLE Empresas
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	IdFuncionario INT FOREIGN KEY REFERENCES Funcionarios(IdFuncionario),
	Nome VARCHAR(100)
)
GO
--ALTERA A TABELA
ALTER TABLE Funcionarios

--EXCLUI A COLUNA
DROP COLUMN Nome;

--EXCLUI A TABELA
DROP TABLE Funcionarios;

--EXCLUI A DATABASE
DROP DATABASE TESTE;

